### ISSUE TITLE
Doesn't Work on iOS 12.2

### ISSUE THREAD

**Issue by paramores** [RecoveryOutlet/twttr#1]
**Describe the bug**
When I was on iOS 12.1.1 beta 3 this tweak worked perfectly, but now that I upgraded to iOS 12.2, the Twitter app's elements don't get colored anymore. I would try downgrading to a lower version of Twitter, but App Admin is not supported yet for 12.2.

**Tweak Version**
 - 1.0.3

**Device & iOS Version:**
 - iPhone 6s+
-  iOS 12.2

**Twitter Version:**
- 7.54.8

**Comment by atebitsy-old** [comment]
have you gone into "twttr settings" and selected the mode you wanted and gone into each section and enabled the switches??

**Comment by paramores** [comment]
I disabled and enabled all of the switches again and it began working; sorry for the inconvenience.

**Comment by atebitsy-old** [comment]
No problem I'm glad it's working now
